#!/bin/bash

BIN_PATH=$HOME/.config/i3scripts/
PULSECTL=$BIN_PATH/pulsectl.py

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  $PULSECTL -r 5 &
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  $PULSECTL -m
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  $PULSECTL -l 5 &
fi

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "${volume}%"
  echo "${volume}%"
  echo ""
else
  echo "MUTE"
  echo "MUTE"
  echo ""
fi
