#!/usr/bin/env bash
# 
# Power management and session handler script
#

# load function library
source $HOME/.config/i3scripts/helper.sh

case "$1" in
    lock)
        i3_lock
        ;;
    logout)
        i3_logout
        ;;
    suspend)
        i3_suspend "suspend"
        ;;
    hibernate)
        i3_suspend "hibernate"
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
