#!/usr/bin/env bash
# 
# Power management and session handler script
#

# load function library
source $HOME/.config/i3scripts/helper.sh

case "$1" in
    lock)
        info "[$(date)] - Calling i3lock..." $I3LOG
        i3_lock
        ;;
    logout)
        info "[$(date)] - Logging out of i3..." $I3LOG
        i3_logout
        ;;
    suspend)
        info "[$(date)] - Suspend to ram..." $I3LOG
        i3_suspend "suspend"
        ;;
    hibernate)
        info "[$(date)] - Starting Hibernation..." $I3LOG
        i3_suspend "hibernate"
        ;;
    reboot)
        info "[$(date)] - Rebooting via systemd..." $I3LOG
        systemctl reboot
        ;;
    shutdown)
        info "[$(date)] - Shutting down via systemd..." $I3LOG
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
