# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# hey OSX, i want to use bash nonetheless, so shut up please
export BASH_SILENCE_DEPRECATION_WARNING=1

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

export TERM="xterm-256color"
# fix for badly broken java apps
export _JAVA_AWT_WM_NONREPARENTING=1

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`gdircolors -b`"
    #alias ls='ls --color=auto'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
export EDITOR="nvim"
export SSH_KEYS_HOMEDIR="${HOME}/.ssh"

# override the dreaded XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME/.config"

# PATH
PATH=$PATH:$GOPATH/bin:/home/marco/.local/bin/:${HOME}/.krew/bin
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Fuzzy finder
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# remap clearscreen
bind '"\C-l": clear-screen'

# w3m default homepage
WWW_HOME="https://start.duckduckgo.com"
export WWW_HOME

# GPG Agent stuff
GPG_TTY=$(tty)
export GPG_TTY

# source functions
source ~/Work/dotfiles/bash/bash_prompt_functions

# set vi mode
set -o vi

# Draw PS1
PROMPT_COMMAND=draw_ps1

